# Generated by Django 4.1 on 2022-08-24 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TelemetryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='variables',
            new_name='variable',
        ),
    ]
