# Generated by Django 4.1 on 2022-08-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelemetryApp', '0002_rename_variables_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='rpm_motor1',
            field=models.FloatField(default=0, verbose_name='RPM Motor 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variable',
            name='rpm_motor2',
            field=models.FloatField(default=0, verbose_name='RPM Motor 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variable',
            name='rpm_motor3',
            field=models.FloatField(default=0, verbose_name='RPM Motor 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variable',
            name='rpm_motor4',
            field=models.FloatField(default=0, verbose_name='RPM Motor 4'),
            preserve_default=False,
        ),
    ]
